### ISSUE TITLE
[BE] Github Actions CI 스크립트를 gradle-build-action을 통해 개선한다.

### ISSUE THREAD

**Issue by yangdongjue5510** [woowacourse-teams/2022-f12#887]
# 목표
현재는 리눅스 명령어로 gradle build를 하고 있다.
```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: grant execute permission for gradlew
        run: chmod +x gradlew

      - name: gradle build
        run: ./gradlew build
```

gradle-build-action을 사용하면 gradle build에 사용되는 의존성, 로컬 빌드 캐시 등이 캐싱될 수 있다고 한다.
gradle-build-action의 캐싱 기능을 통해 CI 속도를 더 빠르게 할 수 있다.
다음은 github actions CI 공식문서에서 gradle-build-action을 활용한 예시이다.
```yaml
name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
```
# 주의사항(Optional)
실제로 속도가 빨라지는 지 확인해봐야 한다.
